/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "var(--bg-canvas)",
        surface: "var(--bg-surface)",
        subtle: "var(--bg-subtle)",
        elevated: "var(--bg-elevated)",
        hairline: "var(--line-hairline)",
        borderStrong: "var(--line-strong)",
        textPrimary: "var(--text-primary)",
        textSecondary: "var(--text-secondary)",
        textTertiary: "var(--text-tertiary)",
        accent: {
          DEFAULT: "var(--accent-primary)",
          hover: "var(--accent-primary-hover)",
          electric: "var(--accent-electric)",
          subtle: "var(--accent-subtle)",
        },
        semantic: {
          success: "var(--semantic-success)",
          warning: "var(--semantic-warning)",
          danger: "var(--semantic-danger)",
          info: "var(--semantic-info)",
        },
        cockpit: {
          canvas: "var(--cockpit-canvas)",
          surface: "var(--cockpit-surface)",
          subtle: "var(--cockpit-subtle)",
          border: "var(--cockpit-border)",
          text: "var(--cockpit-text)",
          muted: "var(--cockpit-text-muted)",
        },
        twin: {
          bg: "var(--twin-bg)",
          card: "var(--twin-card)",
          border: "var(--twin-border)",
          cyan: "var(--twin-cyan)",
          indigo: "var(--twin-indigo)",
          white: "var(--twin-white)",
          slate: "var(--twin-slate)",
          tertiary: "var(--twin-tertiary)",
          success: "var(--twin-success)",
          warning: "var(--twin-warning)",
          danger: "var(--twin-danger)",
        },
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        display: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      borderRadius: {
        xl: "12px",
        lg: "8px",
        md: "6px",
        sm: "4px",
        DEFAULT: "6px",
      },
      boxShadow: {
        panel: "0 1px 2px 0 rgba(0, 0, 0, 0.03)",
        card: "0 1px 3px 0 rgba(0, 0, 0, 0.04), 0 1px 2px -1px rgba(0, 0, 0, 0.03)",
        dropdown: "0 4px 16px -2px rgba(15, 23, 42, 0.08)",
        drawer: "-4px 0 24px rgba(15, 23, 42, 0.08)",
      },
    },
  },
  plugins: [],
};
